export const teamNameMap = new Map<number, string>([
    [140, "Team Spirit"],
    [132, "Natus Vincere"],
    [135, "FaZe Clan"],
    [6, "MOUZ"],
    [1, "G2 Esports"],
    [142, "Team Vitality"],
    [113, "Astralis"],
    [61, "Virtus.pro"],
    [87, "Complexity Gaming"],
    [121, "Cloud9"],
    [126, "HEROIC"],
    [143, "Eternal Fire"],
    [144, "FURIA Esports"],
    [115, "paiN Gaming"],
    [127, "MIBR"],
    [131, "Imperial Esports"],
    [134, "Apeks"],
    [12, "Ninjas in Pyjamas"],
    [48, "Fnatic"],
    [28, "ENCE"],
    [60, "BIG"],
    [74, "SAW"],
    [80, "BetBoom Team"],
    [133, "AMKAL ESPORTS"],
    [85, "9 Pandas"],
    [89, "ECSTATIC"],
    [139, "The MongolZ"],
    [122, "Lynn Vision Gaming"],
    [106, "Grayhound Gaming"],
    [81, "GamerLegion"],
    [59, "forZe"],
    [102, "Preasy Esport"],
    [0, "TBD"],
]);
